---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pdb.yaml
  - ./alerts.yaml
  - ./recording-rules.yaml

configMapGenerator:
  - name: grafana-dashboards-jellyfin
    namespace: media
    files:
      - ./grafana-dashboards/main.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Jellyfin
