apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:Cy9ekt3d4UmIEJh2TDOkxVw=,iv:4MMWhT6RAZvhaYP2H0zUOKBduN4O+pYguV+Ih4QTfGY=,tag:hVAEG9Yx2UHrgvoF84fLkw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:JLJNt4cw4sBI5Nv5/SiwvNtuCNCylF22Ow==,iv:C5EqG4QnNhseM3HC/LclBMHRiao8e+XGNwfUS91YIm4=,tag:kbzhHZplicIKJELQN3RiEA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XFLS2OtvKq42+yaEvusbXCp5Al+1jhfrgA==,iv:6WMPEukGkb1IHbbjFyS4v+8zAmUpRmgxQVQxARNEejQ=,tag:AzlVmEwMlUhyLmh5jOKLDw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:SnIJ5M2zAc5uV0Vdu0m87bbWHEg0fWZwsrczY9aDI0++LyjF,iv:d1hlqvYrjue9sLfzAtAq2iibBDEYAHWtAFOTdmV8hUo=,tag:4tgNQVhNyV+mXFlG9rwSMg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:LDB1LLHqU2a32BEcHlSvQaN4uTa250I9LtMJGnVPN98=,iv:ZDyT/qSgeV54tfwCefytPYZ+WrXC8LDW0MVtHcqswyk=,tag:BKW/2wSyQnpRfrJsWFfM1w==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:cezSj8wse8J+Yuu06XGEKOV0gYnTyv1/nUs/EYZvrlM=,iv:e8CquRlQLW/O0869ntLBoE0ndw4UGMLz+GbGBKjjdc4=,tag:LyXHlC+wqp3OR4g3fyYWqA==,type:str]
    PAGERDUTY_KEY: ENC[AES256_GCM,data:gXBVIA+huR9ihO1tsZdwyvPaomXM+z2pVtiNTyZUBpQ=,iv:2go3MBnr7NtRMhSFa4o9j2SGJKRHrYt58dXghYVeLvA=,tag:nQU+YyVDlttkuRqAGze2Dg==,type:str]
    PAGERDUTY_URL: ENC[AES256_GCM,data:eFTDDpUBGKxBHgjal5SN4HKu7xfp/L9wuZjKRcDtO/MRk/oUJ6lYsWyo4Fpb8KKEFSBZ/CIUrU4Ys2qEsFvCSjXI4MA=,iv:Lgu8PdoP3en9aGPGY4CsigPLivKbC/dgsdOeoyzzdsM=,tag:h/w/UwkuLcybNDw+nf2/IQ==,type:str]
    HEALTHCHECKS_IO_URL: ENC[AES256_GCM,data:iYQxt1O44BILGiXamYmuczMANG7ep3rzQhg7Z1bEuK099wHACDD/wfvDxK7TgQLjT0ko6wxa0DA=,iv:F6/IeNAiQimbD9OMh5Dc+eAKQRusArUT7aJYeaPx9cA=,tag:oOp7HinDerXkUMLiMZ6j3w==,type:str]
    LOCAL_SUBNETS: ENC[AES256_GCM,data:o7p9Z0xlPA1U2zqwQJof9mnOGg5F/y2hVn/TDVv2R7/ynD7IOYa3,iv:RJPcb9FHof1Fyl82fDf3fUFaZhYl3lVN7kH+2ATMeAo=,tag:SFK+6qw3LQOlmoA9FRRYew==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:WAKFORQJx9dP0fUTyp3oFDNReXurw8/x,iv:mXoN3iVUEcVt4HPTf6Y/yiNkQlEX0Hjpo8UAeIyDHwo=,tag:balRXPxhY8aYM4E1ZV9+pA==,type:str]
    JELLYFIN_EXPORTER_API_KEY: ENC[AES256_GCM,data:1LG1LN2b8yGsdH/pj8r+azMBvfyvesYcxO+uVDGJWs8=,iv:xH1/LibsycdJD2gK0nh9S4WhKBTtl7XNw32BRRuiyCI=,tag:oLHDrZIJghcEZIEGXmOeag==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZGdPRjFJaW9HTVV2Tjc1
            Qi83eko5K0pHOW5pVFExN0pxWUdveUNDa3dnCjhaemEvV2N1eFZjZ2M3cm9jVHRI
            NXYvNlJ1WkI5aHBGczN6SWxtV3M2cDgKLS0tIFpveVhqWHVPK2kzNGNiNFNFS0V5
            WDZJZkhCNWMxaUJJQzZSeFlMeGVvMEUKa/OUewcfpAQyx9OtEIDb3q9BUiERuYnM
            TsnG3zXTIp4am6iR9uSZu/V6ZCRoHJc+4Fjfa6mfR/mvWNAuCn2nEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T15:08:54Z"
    mac: ENC[AES256_GCM,data:reeQ8LPyUstDn8QCCnoy7YyohtI7blxHfk8cKA2T6GMitIzqC3K958s5uHKiPLK5fX04jDhferVRwxCR6QIlHKl+UhXUosK4c7tcIFppHYsbYkxXvitC8JBSlVgfWEIE4SAkJQYrJ/H/gqo+IZIHnyFh7c3FJ1Euv+fkkiF5uDM=,iv:Exi8I9s77AG81I3JfW9LBquLyFQ+nSFyyJMFy1kK4Xs=,tag:jv22MELxrNUCip5NgbTzlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
